services:
  postgres:
    image: postgres:15-alpine
    container_name: ai4db_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mvp_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mvp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mvp_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  ollama:
    container_name: ollama
    image: ollama/ollama
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - mvp_network
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mvp_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_APP_USERNAME=${MONGO_APP_USERNAME}
      - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
      - DOCKER_ENV=true
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mvp_network
    restart: unless-stopped

# Définition des volumes
volumes:
  postgres_data:
  redis_data:
  mongodb_data:

# Définition des réseaux
networks:
  mvp_network:
    driver: bridge
